create table d3datas(
	id integer primary key,
	name varchar(50),
	data varchar(50),
	send varchar(50),
	open varchar(50),
	clickpc varchar(50),
	clickpcnumber varchar(50),
	clicksp varchar(50),
	clickspnuymber varchar(50),
	sendclick varchar(50),
	sendopen varchar(50),
	favorite varchar(50),
	apply varchar(50),
	applypass varchar(50), 
);